AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  f0020vacationdays

  0020-vacation-days

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 50
    Runtime: java11
    MemorySize: 512
    # Integration with AWS X-Ray https://docs.aws.amazon.com/lambda/latest/dg/java-tracing.html
    Tracing: Active
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
    # https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html
    # https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/
    ProvisionedConcurrencyConfig:
      ProvisionedConcurrentExecutions: 5

Resources:
  F0020VacationDaysMapRequestHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: F0020VacationDaysMapRequestHandler
      CodeUri: f0020vacationdays
      Handler: .F0020VacationDaysMapRequestHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Tracing: Active # Tracing https://docs.aws.amazon.com/lambda/latest/dg/java-tracing.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        F0020VacationDaysMapRequestHandler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /apply/f0020-vacation-days
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  F0020VacationDaysMapRequestHandlerApi:
    Description: "API Gateway endpoint URL for Prod stage for F0020VacationDaysMapRequestHandler"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/apply/f0020-vacation-days"
  F0020VacationDaysMapRequestHandler:
    Description: "ARN of F0020VacationDaysMapRequestHandler"
    Value: !GetAtt F0020VacationDaysMapRequestHandler.Arn
  F0020VacationDaysMapRequestHandlerIamRole:
    Description: "Implicit IAM Role created for F0020VacationDaysMapRequestHandler"
    Value: !GetAtt F0020VacationDaysMapRequestHandlerRole.Arn

